"""Adicionar coluna reservado na tabela exemplar

Revision ID: 2f50e03ba106
Revises: 
Create Date: 2024-11-08 21:06:08.806523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f50e03ba106'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exemplar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exemplar', schema=None) as batch_op:
        batch_op.drop_column('reservado')

    # ### end Alembic commands ###
