"""Adiciona funcionalidade de disponibilidade do livro

Revision ID: b980726405a2
Revises: 2f50e03ba106
Create Date: 2024-11-18 23:35:04.796445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b980726405a2'
down_revision = '2f50e03ba106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exemplar')
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inclusao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('disponivel', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reservado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_column('reservado')
        batch_op.drop_column('disponivel')
        batch_op.drop_column('data_inclusao')

    op.create_table('exemplar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_inclusao', sa.DATETIME(), nullable=True),
    sa.Column('disponivel', sa.BOOLEAN(), nullable=True),
    sa.Column('livro_id', sa.INTEGER(), nullable=True),
    sa.Column('reservado', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
